### PR TITLE
Bug 1861917: Render cluster-policy-controller for bootstrap

### PR DESCRIPTION
**Pull request by tnozicka**
Having cluster-policy-controller available at bootstrap will allow starting components on other runlevels without having to wait for KCM to deploy and start CPC.

Follow up to https://github.com/openshift/installer/pull/4131 and https://github.com/openshift/cluster-kube-controller-manager-operator/pull/443

/cc @soltysh @deads2k

### CODE REVIEW

**Comment by tnozicka** [comment]
Looks like it's working, the e2e-aws took [~1h26m](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/446/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/1303032458492514304) while the previous jobs take about 1h34m-1h38m

Looking specifically at install time that is:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/446/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/1303032458492514304/artifacts/e2e-aws/ipi-install-install/.openshift_install.log
```
time="2020-09-07T18:47:10Z" level=debug msg="Time elapsed per stage:"
time="2020-09-07T18:47:10Z" level=debug msg="    Infrastructure: 8m29s"
time="2020-09-07T18:47:10Z" level=debug msg="Bootstrap Complete: 6m18s"
time="2020-09-07T18:47:10Z" level=debug msg=" Bootstrap Destroy: 1m12s"
time="2020-09-07T18:47:10Z" level=debug msg=" Cluster Operators: 17m34s"
time="2020-09-07T18:47:10Z" level=info msg="Time elapsed: 33m41s"
```
vs. previous
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/443/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/1301287505445785600/artifacts/e2e-aws/ipi-install-install/.openshift_install.log
```
time="2020-09-02T23:16:37Z" level=debug msg="Time elapsed per stage:"
time="2020-09-02T23:16:37Z" level=debug msg="    Infrastructure: 7m22s"
time="2020-09-02T23:16:37Z" level=debug msg="Bootstrap Complete: 6m41s"
time="2020-09-02T23:16:37Z" level=debug msg=" Bootstrap Destroy: 1m1s"
time="2020-09-02T23:16:37Z" level=debug msg=" Cluster Operators: 23m5s"
time="2020-09-02T23:16:37Z" level=info msg="Time elapsed: 38m19s"
```

**Comment by tnozicka** [comment]
hm, I still see:

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
@tnozicka is it possible that there still is a delay between we run the controller and when they get allowed to run, I wouldn't expect this fix to solve this immediately, only to significantly limit the scope of the problem, no?

**Comment by tnozicka** [comment]
possible, weird that the timings match the BZ but on the other hand the start up timings show ~5m speed up https://github.com/openshift/cluster-kube-controller-manager-operator/pull/446#issuecomment-688641937

**Pull request merged**
