### PR TITLE
use new featuregate API

### PR DESCRIPTION
**Pull request by deads2k**
This fixes the issue at runtime, but not at render time.  Yet.

proof of https://github.com/openshift/library-go/pull/1468

/hold for real bump

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Something wrong in CI, logs from KCMO indicate it's not picking up feature gate status
```
E0425 00:39:41.965296       1 simple_featuregate_reader.go:303] cluster failed with : missing desired version "4.14.0-0.ci.test-2023-04-24-235643-ci-op-gl07gjib-latest" in featuregates.config.openshift.io/cluster
E0425 00:40:21.492699       1 starter.go:86] timed out waiting for FeatureGate detection
W0425 00:40:21.492727       1 builder.go:106] graceful termination failed, controllers failed with error: timed out waiting for FeatureGate detection
```
Looking at the config operator, seems it is `config-operator version v0.0.0-alpha.0-458-g56d61e7-56d61e71` which does not yet include the changes from the required PR.

Will retest all, hopefully CI builds have caught up now

/retest

**Comment by deads2k** [comment]
preinstall failure

/retest

**Comment by deads2k** [comment]
I'll accept a later revert if need be, but this is the first consumer we need for the CCM migration.

**Pull request merged**
