### PR TITLE
[release-4.5] Bug 1851390: Fix port check

### PR DESCRIPTION
**Pull request by tnozicka**
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/421

/cc @soltysh

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
for 4.5 pick of https://github.com/openshift/images/pull/19

**Comment by Gal-Zaidman** [comment]
Can you take a look at
https://bugzilla.redhat.com/show_bug.cgi?id=1853889

I suspect that this will break ovirt for 4.5

**Comment by tnozicka** [comment]
> I suspect that this will break ovirt for 4.5

This isn't claiming new ports so I don't see how. This comment seems to indicate it it was ovirt bug https://bugzilla.redhat.com/show_bug.cgi?id=1853889#c9

**Pull request merged**
