### PR TITLE
 [release-4.13] OCPBUGS-11353: AWS should not use external-cloud-volume-plugin post CSI migration

### PR DESCRIPTION
**Pull request by elmiko**
updated azure unit tests for 4.13 to reflect tech preview status.

### CODE REVIEW

**Comment by elmiko** [comment]
this is a continuation of #722

**Comment by ingvagabund** [comment]
/approve
/label backport-risk-assessed
/assign @jsafrane @bertinatto
for final tag from storage pov

**Comment by kasturinarra** [comment]
@huali9 I have seen that you have premerge tested this bug, shall i go a head and add qe-approved label ? is that okay ? Could you please help confirm ? Thanks !!

**Comment by huali9** [comment]
@kasturinarra Yes, you can go a head and add qe-approved label, but I have added qe-approved label https://github.com/openshift/cluster-kube-controller-manager-operator/pull/734#issuecomment-1539316426 before, should we add that again?

**Comment by kasturinarra** [comment]
> @kasturinarra Yes, you can go a head and add qe-approved label, but I have added qe-approved label [#734 (comment)](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/734#issuecomment-1539316426) before, should we add that again?

@huali9 not qe-approved label, we should add qe-cherry-pick-approved label for it to get merged into the 4.13 branch

**Comment by huali9** [comment]
Sorry @kasturinarra I missed that, let me add that label, thanks!
/label cherry-pick-approved

**Comment by huali9** [comment]
> @huali9: Can not set label cherry-pick-approved: Must be member in one of these teams: []

@kasturinarra Can you help to add that label?

**Pull request merged**
