### PR TITLE
OCPBUGS-21722: bump(openshift/api|client-go|library-go) to pick up http2 disablement

### PR DESCRIPTION
**Pull request by soltysh**
/hold

### CODE REVIEW

**Comment by soltysh** [comment]
Tested using:
```
$ for PROTO in h3 h2 http/1.1 http/1.0; do oc -n openshift-kube-controller-manager-operator exec deployment/kube-controller-manager-operator -- openssl s_client -connect localhost:8443 -alpn "${PROTO}" 2>/dev/null | grep -i alpn; done
No ALPN negotiated
No ALPN negotiated
ALPN protocol: http/1.1
No ALPN negotiated
```
it works as expected
/hold cancel

**Comment by atiratree** [comment]
/retitle OCPBUGS-21722: bump(openshift/api|client-go|library-go) to pick up http2 disablement

**Pull request merged**
