### PR TITLE
Bug 1954790: pdb: Increase PDBAtLimit timeout

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Increase the timeout for PodDisruptionBudgetAtLimit
alert as this warning level and as per the conventions
mentioned at:

https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#warning-alerts

In future, we can have separate alerts for OCP specific components
and user workload specific components.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by vrutkovs** [comment]
Upgrade jobs:
* [test upgrade 4.8.0-fc.8 https://github.com/openshift/cluster-kube-controller-manager-operator/pull/534 aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1402659362740113408)
* [test upgrade 4.7 https://github.com/openshift/cluster-kube-controller-manager-operator/pull/534 aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1402659249154166784)

**Comment by bparees** [comment]
this doesn't make things worse and it unblocks CI, so we should merge it while we continue to evaluate how to improve this alert more generally.  @ravisantoshgudimetla can you create a new bug that's more generic for "pdbatlimit alert has insufficient discrimination" so we can continue to track improving it (or potentially getting rid of it)?

/override ci/prow/e2e-upgrade

**Comment by ravisantoshgudimetla** [comment]
The upgrade test is bound to fail because alert(from old code) would have been triggered by the time new alert is deployed.

Quoting @wking:

    master tips launch (old alert code)
    cluster begins updating
    MCO rolls the pools
    Alert fires
    we get up to 90, and the new alert code rolls out
    Too late, test suite is already mad

**Comment by ravisantoshgudimetla** [comment]
> this doesn't make things worse and it unblocks CI, so we should merge it while we continue to evaluate how to improve this alert more generally. @ravisantoshgudimetla can you create a new bug that's more generic for "pdbatlimit alert has insufficient discrimination" so we can continue to track improving it (or potentially getting rid of it)?


Yes, I can create one.

**Pull request merged**
