### PR TITLE
Revert "[release-4.14] OCPBUGS-19553: Update static pod manifests perms"

### PR DESCRIPTION
**Pull request by DennisPeriquet**
[TRT-1263](https://issues.redhat.com//browse/TRT-1263)

Per [Openshift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert) we are reverting this breaking change to get 4.14 nightly payloads flowing again.

This change is breaking
* 4.14 nightly payload: https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-09-25-152041

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result to confirm the fix has corrected the problem:

/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

CC: @ardaguclu

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

The next payload cleared. I'm not sure there's a regression here.

Your /payload command attempted to aggregate an aggregated job, not the sub-job. Thankfully that didn't seem to work.

**Comment by DennisPeriquet** [comment]
> /hold
> 
> The next payload cleared. I'm not sure there's a regression here.
> 
> Your /payload command attempted to aggregate an aggregated job, not the sub-job. Thankfully that didn't seem to work.

fixed the /payload command in the summary -- thx

**Comment by DennisPeriquet** [comment]
two accepted 4.14 nightlies (without this revert):

https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-09-26-080111
https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-09-26-021547

**Pull request closed without merging**
