### PR TITLE
[release-4.8] bug 1981633: allow upgraded clusters to use the vulnerable service-ca.crt

### PR DESCRIPTION
**Pull request by deads2k**
4.8 pick of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/546

The pick **was not clean**.

requires 
1. https://github.com/openshift/kubernetes/pull/856
2. https://github.com/openshift/service-ca-operator/pull/170 and
3.  https://github.com/openshift/kubernetes/pull/857 

to have proof on an 4.7 to 4.8 upgrade job.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by deads2k** [comment]
the others have now merged

/test all

**Comment by deads2k** [comment]
upgrade jobs shows using vulnerable
aws jobs shows using secure

/hold cancel

**Pull request merged**
