### PR TITLE
Revert "Merge pull request #554 from atiratree/cpc-metrics"

### PR DESCRIPTION
**Pull request by deads2k**
This reverts commit 42db0aa02e7c3e4581bf919cdde0fef332db7b2d, reversing
changes made to 59c8dae2280f69f535a2f5f349b693b674729cd0.

payload promotion failure on https://amd64.ocp.releases.ci.openshift.org/releasestream/4.10.0-0.ci/release/4.10.0-0.ci-2021-11-19-163531 causing a flaky failure of targetDown on cluster-policy-controller.

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-aws-ovn-upgrade-4.[…]-openshift-release-analysis-aggregator/1461737712246591488 is an example

The near certain cause is https://github.com/openshift/cluster-kube-controller-manager-operator/pull/554 .  It shows up in the PR test history too: https://prow.ci.openshift.org/pr-history/?org=openshift&repo=cluster-kube-controller-manager-operator&pr=554

1. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/554/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/1443291747927986176
2. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/554/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/1443252779547103232
3. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/554/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/1443169310972317696

Now how this can be intermittent (flaky) and how it can fail without showing up in the monitoring logs (I checked in loki), I do not understand.  But I think #554 pretty clearly added it and you'll need to run 10 periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade to unrevert.

I did consider possibilities like a monitoring failure or a networking failure, but it would be an incredible coincidence that this shows up shortly after #554 merges and no other target is consistently down

### CODE REVIEW

**Comment by deads2k** [comment]
infra

/retest

**Comment by deads2k** [comment]
It's a Friday leading up to a holiday week.  I've weighed the options and decided it's better to merge this revert to get past this payload promotion problem instead of waiting until Monday.  Adding the label.

**Comment by wking** [comment]
David and I were poking around in [this run][1], and the timeline is:

* 17:54:20Z, `cluster-policy-controller` Service created
* 17:54:32, `up==0`
* 18:56:04Z, `cluster-policy-controller` ServiceMonitor created
* 18:56:19Z, update completed

Those `up` scrape errors lead to the `TargetDown` alert.  The issue is that before #554, the `kube-controller-manager` ServiceMonitor [lacked a `selector`][2].  So right after the `cluster-policy-controller` Service was created, Prom started attempting to scrape it too.  `endpoints` looks the same for both ServiceMonitors though... and that shows another bug: I expect you don't want `serverName: kube-controller-manager.openshift-kube-controller-manager.svc` for the ServiceMonitor that's scraping `cluster-policy-controller.openshift-kube-controller-manager.svc`.  Probably go over the rest of the incoming ServiceMonitor to check for other copy/paste issues like that.

And because we'll want 4.9 -> 4.10 updates to be clean with no `TargetDown` firing, we'll want to roll this out in stages like:

1. This revert.
2. `master` PR to fill in `selector` for the `kube-controller-manager` ServiceMonitor.
3. Backport that PR to 4.9.
4. That PR ships in a 4.9.z.
5. Updates team creates a 4.10 entry for [build suggestions][3] that sets `minor_min` to the 4.9.z that shipped the `selector` scoping.
6. `master` PR to add the `cluster-policy-controller` Service and ServiceMonitor.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1461737702696161280
[2]: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/554/files#diff-f2b12d2453c7da09ecf597197907e580c1c6dcb2eeef688e708bbaa3b5be4b99R78
[3]: https://github.com/openshift/cincinnati-graph-data/tree/master/build-suggestions

**Comment by atiratree** [comment]
> And because we'll want 4.9 -> 4.10 updates to be clean with no `TargetDown` firing, we'll want to roll this out in stages like:
> 
> 1. This revert.
> 2. `master` PR to fill in `selector` for the `kube-controller-manager` ServiceMonitor.
> 3. Backport that PR to 4.9.
> 4. That PR ships in a 4.9.z.
> 5. Updates team creates a 4.10 entry for [build suggestions](https://github.com/openshift/cincinnati-graph-data/tree/master/build-suggestions) that sets `minor_min` to the 4.9.z that shipped the `selector` scoping.
> 6. `master` PR to add the `cluster-policy-controller` Service and ServiceMonitor.

@wking @deads2k Thanks for looking into this. This solution should indeed prevent TargetDown alert firing during the upgrades (please see https://github.com/openshift/cluster-kube-controller-manager-operator/pull/575 for a PR). Unfortunately there is also an installer issue with closed ports that needs to be fixed, since the alerts are firing even after the successful upgrade.

>  I expect you don't want `serverName: kube-controller-manager.openshift-kube-controller-manager.svc` for the ServiceMonitor that's scraping `cluster-policy-controller.openshift-kube-controller-manager.svc`. Probably go over the rest of the incoming ServiceMonitor to check for other copy/paste issues like that.

We are reusing the same certificate for CPC so it is necesssary for server name to be the same as KCM

```
* Server certificate:
*  subject: CN=kube-controller-manager.openshift-kube-controller-manager.svc
```

**Comment by atiratree** [comment]
> Unfortunately there is also an installer issue with closed ports that needs to be fixed, since the alerts are firing even after the successful upgrade.

probably a mistake on my part, investigating...

**Comment by atiratree** [comment]
^ still prevalent - ports opened in https://github.com/openshift/installer/pull/5105 are not opened on cluster upgrade

**Pull request merged**
