### PR TITLE
Bug 2037856: bump library go 

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by ravisantoshgudimetla** [comment]
/hold

need https://coreos.slack.com/archives/CC3CZCQHM/p1642446464431500?thread_ts=1641487878.025300&cid=CC3CZCQHM needs to be addressed

**Comment by ravisantoshgudimetla** [comment]
Running the e2e tests locally and they passed:

```
=== RUN   TestOperatorNamespace
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
--- PASS: TestOperatorNamespace (0.14s)
=== RUN   TestPodDisruptionBudgetAtLimitAlert
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
W0124 11:04:17.383045   60385 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0124 11:04:17.416605   60385 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
--- PASS: TestPodDisruptionBudgetAtLimitAlert (44.85s)
=== RUN   TestTargetConfigController
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
=== RUN   TestTargetConfigController/targetconfigcontroller_KCM_config
=== RUN   TestTargetConfigController/targetconfigcontroller_cluster_policy_controller_config
=== RUN   TestTargetConfigController/targetconfigcontroller_csr-signer-ca
--- PASS: TestTargetConfigController (30.33s)
    --- PASS: TestTargetConfigController/targetconfigcontroller_KCM_config (5.08s)
    --- PASS: TestTargetConfigController/targetconfigcontroller_cluster_policy_controller_config (15.18s)
    --- PASS: TestTargetConfigController/targetconfigcontroller_csr-signer-ca (10.07s)
=== RUN   TestResourceSyncController
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
=== RUN   TestResourceSyncController/resourcesynccontroller_csr-controller-ca
=== RUN   TestResourceSyncController/resourcesynccontroller_service-ca
=== RUN   TestResourceSyncController/resourcesynccontroller_client-ca
=== RUN   TestResourceSyncController/resourcesynccontroller_aggregator-client-ca
--- PASS: TestResourceSyncController (25.30s)
    --- PASS: TestResourceSyncController/resourcesynccontroller_csr-controller-ca (10.07s)
    --- PASS: TestResourceSyncController/resourcesynccontroller_service-ca (5.07s)
    --- PASS: TestResourceSyncController/resourcesynccontroller_client-ca (5.08s)
    --- PASS: TestResourceSyncController/resourcesynccontroller_aggregator-client-ca (5.08s)
=== RUN   TestKCMRecovery
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
--- PASS: TestKCMRecovery (5.08s)
=== RUN   TestLogLevel
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
--- PASS: TestLogLevel (153.26s)
=== RUN   TestSATokenSignerControllerSyncCerts
Found configuration for host https://api.ci-ln-xxst9p2-76ef8.origin-ci-int-aws.dev.rhcloud.com:6443.
    satokensigner_test.go:30: Waiting for true, false, false
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: true  DegradedOK: true
    satokensigner_test.go:37: Waiting for true, true, false
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: true  DegradedOK: true
    satokensigner_test.go:44: Waiting for true, false, false
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
	    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true

    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: false  DegradedOK: true
    cluster_operator.go:40: ClusterOperator/kube-controller-manager: AvailableOK: true  ProgressingOK: true  DegradedOK: true
--- PASS: TestSATokenSignerControllerSyncCerts (182.18s)
PASS
ok  	github.com/openshift/cluster-kube-controller-manager-operator/test/e2e	442.095s
```

**Pull request merged**
