### PR TITLE
Bug 1881534: Use internal load balancer instead of localhost 4.5

### PR DESCRIPTION
**Pull request by tnozicka**
/cc @soltysh @deads2k 

Backport of #441 (since #431 was reverted)

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/retest

**Comment by markmc** [comment]
(patch manager) The PR linked from the 4.6 bug is #431 which is confusing. I see now that #431 was reverted and a new fix was merged in #441. I would have appreciated that explained clearly in the PR description. Added now.

**Comment by markmc** [comment]
/retitle Bug 1881534: Use internal load balancer instead of localhost 4.5

**Pull request merged**
