### PR TITLE
Bug 1809368: bump openshift/api to remove IPv6DualStack feature flag

### PR DESCRIPTION
**Pull request by danwinship**
The IPv6DualStack has bugs in 1.17/4.4 even in single-stack clusters so we need to stop setting it.

----

bump: openshift/api

In particular, to get

openshift/api#585: config: disable IPv6DualStack feature flag

so we don't launch kube-controller-manager with that (still-broken) feature

Also includes:

openshift/api#557: create the IBMCLoudPlatform type for the ingress operator try2
openshift/api#570: Clarify image config doc
openshift/api#569: Enable overriding service account issuer for bound tokens
openshift/api#527: Add kubebuilder annotations to the network types
openshift/api#574: add deprecaction notice for build pipeline strategy
openshift/api#582: config/v1/types_proxy: Clarify trustedCA semantics
openshift/api#583: Clarify FROM behavior in builds
openshift/api#573: Add CRD generator documentation to Readme
openshift/api#576: Remove Description from CLI output to improve its display
openshift/api#589: Add missing enum validations
openshift/api#583: operator/ingress: add dnsrecord type

### CODE REVIEW

**Comment by danwinship** [comment]
Repeated e2e-aws failures seem bad...

must-gather logs from one of them show a bunch of:

```
Mar 03 12:18:18 ip-10-0-8-255 bootkube.sh[12564]: Rendering Kubernetes Controller Manager core manifests...
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: panic: Failed to load "/usr/share/bootkube/manifests/config/bootstrap-config-overrides.yaml": open /usr/share/bootkube/manifests/config/bootstrap-config-overrides.yaml: no such file or directory
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: goroutine 1 [running]:
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/openshift/cluster-kube-controller-manager-operator/pkg/cmd/render.mustReadTemplateFile(0xc0006be2d0, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/openshift/cluster-kube-controller-manager-operator@/pkg/cmd/render/render.go:233 +0x1df
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/openshift/cluster-kube-controller-manager-operator/pkg/cmd/render.(*renderOpts).Run(0xc000369200, 0x0, 0x0)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/openshift/cluster-kube-controller-manager-operator@/pkg/cmd/render/render.go:209 +0x2d4
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/openshift/cluster-kube-controller-manager-operator/pkg/cmd/render.NewRenderCommand.func1.1(0xc0007076c0)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/openshift/cluster-kube-controller-manager-operator@/pkg/cmd/render/render.go:48 +0x4e
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/openshift/cluster-kube-controller-manager-operator/pkg/cmd/render.NewRenderCommand.func1(0xc0002cd400, 0xc0006c3540, 0x0, 0x5)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/openshift/cluster-kube-controller-manager-operator@/pkg/cmd/render/render.go:58 +0x11d
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/spf13/cobra.(*Command).execute(0xc0002cd400, 0xc0006c34f0, 0x5, 0x5, 0xc0002cd400, 0xc0006c34f0)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ccc80, 0xc000054040, 0xc0002ccc80, 0x6)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/spf13/cobra@v0.0.5/command.go:864
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]: main.main()
Mar 03 12:18:19 ip-10-0-8-255 bootkube.sh[12564]:         github.com/openshift/cluster-kube-controller-manager-operator@/cmd/cluster-kube-controller-manager-operator/main.go:38 +0x18e
```

**Comment by deads2k** [comment]
@danwinship this shows a zero diff change.

**Comment by danwinship** [comment]
Yes, I was trying to figure out why every run of e2e-aws on this PR has failed with [seemingly-kcm-related bootstrap errors](https://github.com/openshift/cluster-kube-controller-manager-operator/pull/355#issuecomment-593974478) even though there don't seem to be any changes in the bump that should have broken anything. So I reverted everything except the feature gate change and tested again, and it still failed... so I tried reverting that too and testing again, but then hit an infra flake.

**Comment by soltysh** [comment]
Done in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/359.

**Pull request closed without merging**
