### PR TITLE
Bug 1948431: Bump openshift api version to get CSIMigrationXXX feature gates

### PR DESCRIPTION
**Pull request by gnufied**
Bump openshift/api version

Note: this is needed for CSI migration feature to work in OCP 4.8.
Goal of this PR is to apply --feature-gate=CSIMigrationAWS=true,CSIMigrationOpenStack=true to KCM when TechPreviewNoUpgrade featureSet is enabled, which was introduced in openshift/api#880

### CODE REVIEW

**Comment by gnufied** [comment]
cc @openshift/sig-storage @deads2k

**Comment by jsafrane** [comment]
/retitle Bug 1948431: Bump openshift api version to get CSIMigrationXXX feature gates

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
