### PR TITLE
[release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR bumps library-go to fetch the changes come with;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

### CODE REVIEW

**Comment by ardaguclu** [comment]
@atiratree could you PTAL?(and that would be great adding backport-risk-assessed if you have powers). Thanks.

**Comment by atiratree** [comment]
/lgtm
but don't have the powers for backport-risk-assessed. You need to ping @soltysh or @ingvagabund

**Review by soltysh — APPROVED** [review]
/label backport-risk-assessed

**Pull request merged**
