### PR TITLE
Bug 1826259: fix ingress CA cert location

### PR DESCRIPTION
**Pull request by soltysh**
/assign @tnozicka 

To pick up https://github.com/openshift/library-go/pull/775: `Bug 1826259: fix ingress CA cert location`

### CODE REVIEW

**Comment by soltysh** [comment]
I'm tracking that `TestSATokenSignerControllerSyncCerts` failure in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/394

**Comment by Miciah** [comment]
Per https://github.com/openshift/cluster-kube-controller-manager-operator/pull/409#issuecomment-625495291,
/cherry-pick release-4.4

**Pull request merged**
