### PR TITLE
Bug 1851398: Check port availability in the same container

### PR DESCRIPTION
**Pull request by tnozicka**
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/421

/cc @soltysh

### CODE REVIEW

**Comment by sdodson** [comment]
/hold
Requires https://github.com/openshift/images/pull/22 first

**Comment by tnozicka** [comment]
/hold cancel
https://github.com/openshift/images/pull/22 is merged

**Review by kasturinarra — COMMENTED** [review]
Tried to verify the bug via cluster bot  and i see that there is no init container and the port is 10257, but not adding lgtm because i see below error when run oc describe on the pod. Not sure why this happens, so will verify it in the nightly build.

State:       Running
      Started:   Wed, 26 Aug 2020 17:34:04 +0530
    Last State:  Terminated
      Reason:    Error
      Message:   ntrollers?allowWatchBookmarks=true&resourceVersion=15648&timeout=5m4s&timeoutSeconds=304&watch=true: dial tcp [::1]:6443: connect: connection refused
E0826 12:04:03.661808       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.ReplicationController: Get https://localhost:6443/api/v1/replicationcontrollers?allowWatchBookmarks=true&resourceVersion=7888&timeout=7m6s&timeoutSeconds=426&watch=true: dial tcp [::1]:6443: connect: connection refused
E0826 12:04:03.662947       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.NetworkPolicy: Get https://localhost:6443/apis/networking.k8s.io/v1/networkpolicies?allowWatchBookmarks=true&resourceVersion=7948&timeout=5m3s&timeoutSeconds=303&watch=true: dial tcp [::1]:6443: connect: connection refused
E0826 12:04:03.663986       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Lease: Get https://localhost:6443/apis/coordination.k8s.io/v1/leases?allowWatchBookmarks=true&resourceVersion=16780&timeout=5m54s&timeoutSeconds=354&watch=true: dial tcp [::1]:6443: connect: connection refused
E0826 12:04:03.665311       1 reflector.go:280] k8s.io/client-go/metadata/metadatainformer/informer.go:89: Failed to watch *v1.PartialObjectMetadata: Get https://localhost:6443/apis/operator.openshift.io/v1/servicecas?allowWatchBookmarks=true&resourceVersion=11977&timeout=9m15s&timeoutSeconds=555&watch=true: dial tcp [::1]:6443: connect: connection refused
I0826 12:04:03.665584       1 leaderelection.go:287] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F0826 12:04:03.665700       1 controllermanager.go:291] leaderelection lost
E0826 12:04:03.740883       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.DaemonSet: Get https://localhost:6443/apis/extensions/v1beta1/daemonsets?allowWatchBookmarks=true&resourceVersion=15019&timeout=8m42s&timeoutSeconds=522&watch=true: dial tcp [::1]:6443: connect: connection refused

      Exit Code:    255
      Started:      Wed, 26 Aug 2020 17:30:16 +0530
      Finished:     Wed, 26 Aug 2020 17:34:03 +0530
    Ready:          True
    Restart Count:  1

**Comment by crawford** [comment]
@tnozicka is the comment above related to this change?

**Comment by tnozicka** [comment]
@kasturinarra @crawford  the isn't related. The errors happen because the localhost apiserver is not up (probably rolling out a revision). KCM has switched to using a LB instead in newer version but this is by design.

**Comment by kasturinarra** [comment]
Thanks tomas for the confirmation & added lgtm to test the pre-merge verification process.

**Pull request merged**
