### PR TITLE
OCPBUGS-31384: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode

### PR DESCRIPTION
**Pull request by p0lyn0mial**
UseSecretUpdateOnly is intended as a short term hack for a very specific use case,
and it works in tandem with a particular carry patch applied to the openshift kube-apiserver.
(https://github.com/openshift/kubernetes/pull/1924)

we will remove this when we migrate all of the affected secret
objects to their intended type: https://issues.redhat.com/browse/API-1800

in short tls secrets used by this operator are reconciled
by multiple controllers ([the cert controller run by the operator](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/pkg/operator/certrotationcontroller/certrotationcontroller.go#L85) and [the same controller run by the recovery pod](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/pkg/cmd/recoverycontroller/cmd.go#L92)) at the same time without any coordination.

the issue is that the secret's crypto material
can be regenerated, which has serious consequences for the platform
as it can break external clients and the cluster itself.

xref: https://github.com/openshift/library-go/pull/1705
xref: https://github.com/openshift/kubernetes/pull/1924

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

requires https://github.com/openshift/kubernetes/pull/1924

**Comment by tkashem** [comment]
/retitle "OCPBUGS-31384: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode"

**Comment by tkashem** [comment]
/retitle OCPBUGS-31384: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode

**Comment by p0lyn0mial** [comment]
`ci/prow/e2e-aws-operator` fails on `CertRotation_CSRSigningCert_Degraded: Secret "csr-signer-signer" is invalid: type: Invalid value: "kubernetes.io/tls": field is immutable` because the secret is created with the old type https://github.com/openshift/cluster-kube-controller-manager-operator/blob/351c1193c7eebb49054a289a17fc25dfc0e0cd73/bindata/bootkube/manifests/secret-csr-signer-signer.yaml#L10

Once https://github.com/openshift/kubernetes/pull/1924 merges the issue should be resolved but as a follow-up we should change the type of the secret for new clusters.

**Comment by ingvagabund** [comment]
> UseSecretUpdateOnly is intended as a short term hack

How long the short is?

**Comment by p0lyn0mial** [comment]
>> UseSecretUpdateOnly is intended as a short term hack

> How long the short is?

We haven't decided yet but we will be working on a fix this release - not sure if we will be able to finish the work.

**Comment by p0lyn0mial** [comment]
`ci/prow/e2e-aws-operator` failed on `TestSATokenSignerControllerSyncCerts` but the cluster was installed. 

It looks like the test is flaky, it also failed on:

- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/796/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator/1772714450818699264

- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/799/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator/1775200522333065216

- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/796/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator/1772278491354501120

**Comment by p0lyn0mial** [comment]
/retest-required

`ci/prow/e2e-aws-operator` failed again on `TestSATokenSignerControllerSyncCerts`

**Comment by p0lyn0mial** [comment]
@tkashem just rebased on top of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/796 PTAL

**Pull request merged**
