### PR TITLE
Add namespace to PDB limit alert

### PR DESCRIPTION
**Pull request by soltysh**
/assign @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
/hold

You might have to get review from monitoring here, the "namespace" label is kind of special (it might be automagic)

**Comment by smarterclayton** [comment]
@s-urbaniak is `namespace` the correct label (I assume it gets renamed to `exported_namespace`)?

**Comment by s-urbaniak** [comment]
(at least for this metric)

**Comment by LiliC** [comment]
Yes the namespace is there and set as the `PodDisruptionBudget` resource ns. 👍 

[source code](https://github.com/kubernetes/kube-state-metrics/blob/e03540f06bfd3a933b2178c975f1f9d1a382ac96/internal/store/poddisruptionbudget.go#L133)

**Comment by soltysh** [comment]
Rebased, after https://github.com/openshift/cluster-kube-controller-manager-operator/pull/308 landed, I will self-tag since this is a simple fix already approved.

**Pull request merged**
