### PR TITLE
OCPBUGS-12709: Reset library-go branch after Azure revert

### PR DESCRIPTION
**Pull request by JoelSpeed**
#721 should not have been reverted as a part of the Azure change, and it is now causing issues with the 1.27 rebase, as it was before.

Library-go merged openshift/library-go#1499 so we can now pin library-go back to master. Azure CCM is still not enabled in library-go so in regards to the Azure revert this should complete that process for this repo

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by bertinatto** [comment]
/retitle  OCPCLOUD-2034: Reset library-go branch after Azure revert #729

**Comment by bertinatto** [comment]
/retitle OCPBUGS-12709: Reset library-go branch after Azure revert

**Pull request merged**
