### PR TITLE
Bug 1946479: manifests: use manual service account mounts

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @stlaz

### CODE REVIEW

**Comment by s-urbaniak** [comment]
/hold
this is up for discussion

**Comment by s-urbaniak** [comment]
xref https://github.com/openshift/kubernetes/pull/714

**Comment by s-urbaniak** [comment]
/hold cancel
fixed the signature changes in library-go

**Review by soltysh — APPROVED** [review]
/approve

**Comment by s-urbaniak** [comment]
e2e failures are related, investigating.

**Pull request merged**
