### PR TITLE
[release-4.14] OCPBUGS-19553: Update static pod manifests perms

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR bumps library-go to get the latest static pod permissions(more specifically https://github.com/openshift/library-go/pull/1576) and this PR also has to bump kube dependencies to 1.27.4.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/jira refresh
/hold 
until 4.15 is updated.

**Comment by ardaguclu** [comment]
@atiratree  could you also PTAL this backport?(we will have to do this for 4.13 and 4.12). Thanks.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
