### PR TITLE
[release-4.4] Bug 1825987: Sync new client cert-key on recovery

### PR DESCRIPTION
**Pull request by tnozicka**
backport of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/400

/cc @deads2k @soltysh @mfojtik

### CODE REVIEW

**Comment by tnozicka** [comment]
/assign @mfojtik 
for cherry-pick label

**Comment by tnozicka** [comment]
@sdodson this should go in asap, anything blocking labeling this?

**Comment by sdodson** [comment]
@tnozicka Does https://github.com/openshift/cluster-kube-controller-manager-operator/pull/402 need to be backported? otherwise this looks fine. Upstream change merged Apr 22, was verified Apr 26.

**Comment by tnozicka** [comment]
> @tnozicka Does #402 need to be backported?

@sdodson Doesn't look like they managed to break it for 4.4 (only master) https://github.com/openshift/cluster-ingress-operator/blob/3d9a5d3/pkg/operator/controller/names.go#L62

**Comment by tnozicka** [comment]
The connection to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/402 on the upstream PR was that is was blocking master merges at the time because the ingress rename PR broke it and that job wasn't gating other repos.

**Pull request merged**
