### PR TITLE
allow upgraded clusters to use the vulnerable service-ca.crt

### PR DESCRIPTION
**Pull request by deads2k**
part 4 of the plan from openshift/service-ca-operator#167

It will require an API update to be safe.

/hold

This should not merge without a real field.

### CODE REVIEW

**Comment by deads2k** [comment]
the other fixes merged, let's see this thing work! ;)

/test all

**Comment by deads2k** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/546/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws-operator-preferred-host/1414923887124156416 has secure service-ca as expected.  Waiting on upgrade now.

**Review by soltysh — APPROVED** [review]
manually verified that upgrade is keeping the old behavior, and new cluster has the new
/lgtm
/hold cancel

**Pull request merged**
