### PR TITLE
WIP Bump library-go

### PR DESCRIPTION
**Pull request by marun**
**NOTE** This PR is based on #334 and will not be reviewable until that PR merges.

/cc @mfojtik

### CODE REVIEW

**Comment by tnozicka** [comment]
/hold
The cert recovery is doing the bump, i dont want to race

**Comment by tnozicka** [comment]
#334

**Comment by marun** [comment]
@tnozicka Glad you noticed the potential conflict. I've rebased this PR on yours and will make ready for review only when yours merges.

**Comment by marun** [comment]
This PR has been superceded by #334

**Pull request closed without merging**
